#!/usr/bin/env node
/**
 * gate.mjs — THE AUTHORITY ON "ARE WE DONE"
 *
 * Ships with the Anvil Loop. Stack-agnostic: it never touches your engine, it only
 * shells out to the tools your project defined and compares numbers to thresholds.
 *
 * This exists because an exit condition written in prose is a suggestion. An agent
 * reading "beauty >= 8" decides whether it is done. A program reading the same thing
 * from anvil.json decides for it, and cannot be argued with.
 *
 *   node tools/gate.mjs                 run every bar, print the table, exit non-zero on fail
 *   node tools/gate.mjs --bar=beauty    run one bar
 *   node tools/gate.mjs --json          machine-readable output
 *   node tools/gate.mjs --approve-change   human sign-off for a changed exit condition
 *
 * Do not edit this file to make a gate pass. That is the one action this whole
 * framework exists to prevent.
 */

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'

const ROOT = process.cwd()
const SPEC = `${ROOT}/anvil.json`
const STATE = `${ROOT}/.anvil`
const LOCK = `${STATE}/gates.lock`
const VERIFIED = `${STATE}/harness-verified.json`

const args = process.argv.slice(2)
const flag = (n) => args.some((a) => a === `--${n}` || a.startsWith(`--${n}=`))
const val = (n) => (args.find((a) => a.startsWith(`--${n}=`)) || '').split('=')[1]
const JSON_OUT = flag('json')

const die = (msg, code = 2) => {
  if (JSON_OUT) console.log(JSON.stringify({ ok: false, error: msg }))
  else console.error(`\n  GATE ERROR — ${msg}\n`)
  process.exit(code)
}

if (!existsSync(SPEC)) die('anvil.json not found — nothing to gate against. See AGENTS.md, SITUATION 1.')
const spec = JSON.parse(readFileSync(SPEC, 'utf8'))
if (!Array.isArray(spec.bars) || spec.bars.length === 0) die('anvil.json declares no bars.')
if (!existsSync(STATE)) mkdirSync(STATE, { recursive: true })

/* ------------------------------------------------------------------ *
 * INVARIANT 12, MECHANISED
 * The loop may sharpen its methods. It may never soften its exit numbers.
 * We hash the bars at first run. If a later run finds a threshold that got
 * EASIER, or a bar that vanished, or the coverage axis narrowed, we refuse
 * to run until a human signs off. An agent cannot approve its own change.
 * ------------------------------------------------------------------ */

const difficulty = (s) => ({
  bars: Object.fromEntries(
    s.bars.map((b) => [b.id, { threshold: b.threshold, compare: b.compare ?? '>=' }])
  ),
  coverage: s.coverage?.members ?? null,
})

const easier = (oldD, newD) => {
  const reasons = []
  for (const [id, o] of Object.entries(oldD.bars)) {
    const n = newD.bars[id]
    if (!n) { reasons.push(`bar "${id}" was removed`); continue }
    // A compare change is only weakening if it loosens. '>=' → '>' is strictly harder.
    if (n.compare !== o.compare) {
      const dir = (c) => (String(c).startsWith('>') ? 'up' : String(c).startsWith('<') ? 'down' : 'other')
      const strict = (c) => c === '>' || c === '<'
      if (dir(n.compare) !== dir(o.compare)) reasons.push(`bar "${id}" comparison direction changed ${o.compare} → ${n.compare}`)
      else if (strict(o.compare) && !strict(n.compare)) reasons.push(`bar "${id}" comparison loosened ${o.compare} → ${n.compare}`)
    }
    const up = (o.compare ?? '>=').startsWith('>')
    if (typeof o.threshold === 'number' && typeof n.threshold === 'number') {
      if (up && n.threshold < o.threshold) reasons.push(`bar "${id}" threshold lowered ${o.threshold} → ${n.threshold}`)
      if (!up && n.threshold > o.threshold) reasons.push(`bar "${id}" threshold raised (weaker) ${o.threshold} → ${n.threshold}`)
    }
  }
  if (oldD.coverage != null && newD.coverage != null && newD.coverage < oldD.coverage)
    reasons.push(`coverage axis narrowed ${oldD.coverage} → ${newD.coverage} members`)
  return reasons
}

const current = difficulty(spec)
const fingerprint = createHash('sha256').update(JSON.stringify(current)).digest('hex').slice(0, 16)

if (flag('approve-change')) {
  writeFileSync(LOCK, JSON.stringify({ fingerprint, difficulty: current, approvedAt: new Date().toISOString(), approvedBy: 'human' }, null, 2))
  console.log(`\n  Exit condition change approved and locked (${fingerprint}).\n`)
  process.exit(0)
}

if (!existsSync(LOCK)) {
  writeFileSync(LOCK, JSON.stringify({ fingerprint, difficulty: current, approvedAt: new Date().toISOString(), approvedBy: 'define' }, null, 2))
} else {
  const lock = JSON.parse(readFileSync(LOCK, 'utf8'))
  if (lock.fingerprint !== fingerprint) {
    const reasons = easier(lock.difficulty, current)
    if (reasons.length) {
      die(
        `EXIT CONDITION WEAKENED — this requires human sign-off.\n\n` +
        reasons.map((r) => `    · ${r}`).join('\n') +
        `\n\n  The loop is not permitted to lower its own bar. If this change is correct,\n` +
        `  a human runs:  node tools/gate.mjs --approve-change`,
        3
      )
    }
    // Harder or lateral — allowed, relock silently.
    writeFileSync(LOCK, JSON.stringify({ fingerprint, difficulty: current, approvedAt: new Date().toISOString(), approvedBy: 'auto (not weaker)' }, null, 2))
  }
}

/* ------------------------------------------------------------------ *
 * INVARIANT 3 — no score is trusted until the harness is proven.
 * ------------------------------------------------------------------ */

if (!existsSync(VERIFIED)) {
  die('harness not verified. Run `node tools/verify-harness.mjs` first.\n' +
      '  Until reproducibility is proven, every number below this line is noise.', 4)
}

/* ------------------------------------------------------------------ *
 * RUN THE BARS
 * ------------------------------------------------------------------ */

const pick = (obj, path) => path.split('.').reduce((o, k) => (o == null ? o : o[k]), obj)

const lastJson = (text) => {
  const lines = text.trim().split('\n')
  for (let i = lines.length - 1; i >= 0; i--) {
    const l = lines[i].trim()
    if (l.startsWith('{') || l.startsWith('[')) { try { return JSON.parse(l) } catch {} }
  }
  try { return JSON.parse(text) } catch { return null }
}

const cmp = (a, op, b) => ({
  '>=': a >= b, '>': a > b, '<=': a <= b, '<': a < b, '==': a === b, '!=': a !== b,
}[op] ?? false)

const only = val('bar')
const bars = only ? spec.bars.filter((b) => b.id === only) : spec.bars
if (only && !bars.length) die(`no bar with id "${only}" in anvil.json`)

const results = []
for (const bar of bars) {
  const op = bar.compare ?? '>='
  const r = { id: bar.id, threshold: bar.threshold, compare: op, actual: null, pass: false, note: '' }
  if (!bar.command) { r.note = 'no command declared — bar is unmeasurable and must not be in the exit condition'; results.push(r); continue }
  try {
    const out = execSync(bar.command, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: (bar.timeoutMs ?? 3_600_000) })
    const parsed = lastJson(out)
    if (parsed == null) { r.note = 'tool emitted no JSON on stdout'; results.push(r); continue }
    const raw = bar.field ? pick(parsed, bar.field) : parsed.value
    if (typeof raw !== 'number') { r.note = `field "${bar.field ?? 'value'}" missing or not a number`; results.push(r); continue }
    r.actual = raw
    r.pass = cmp(raw, op, bar.threshold)
    // INVARIANT 4 — the score is the worst member, never the mean.
    if (parsed.worstMember != null) r.note = `worst: ${parsed.worstMember}`
  } catch (e) {
    r.note = `tool failed: ${String(e.message).split('\n')[0].slice(0, 120)}`
  }
  results.push(r)
}

const allPass = results.length > 0 && results.every((r) => r.pass)

/* ------------------------------------------------------------------ *
 * The loop cannot forget to record a result, because it is not asked to.
 * Every gate run appends itself to .anvil/state.json. journal.mjs renders
 * that into PROGRESS.md and computes stall from it.
 * Skipped for single-bar runs, which are diagnostics rather than gates.
 * ------------------------------------------------------------------ */

if (!only) {
  try {
    const path = `${STATE}/state.json`
    const st = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : { version: 1, history: [], drift: [], amendments: [], log: [] }
    st.history = st.history ?? []
    st.history.push({
      iteration: st.history.length + 1,
      at: new Date().toISOString(),
      fingerprint,
      bars: Object.fromEntries(results.map((r) => [r.id, r.actual])),
      passing: results.filter((r) => r.pass).length,
      total: results.length,
      worstMember: results.map((r) => (r.note.startsWith('worst: ') ? r.note.slice(7) : null)).find(Boolean) ?? null,
      allPass,
    })
    st.updatedAt = new Date().toISOString()
    writeFileSync(path, JSON.stringify(st, null, 2))
    writeFileSync(`${STATE}/last-gate.json`, JSON.stringify({ ok: allPass, fingerprint, bars: results }, null, 2))
  } catch { /* recording must never block the gate */ }
}

if (JSON_OUT) {
  console.log(JSON.stringify({ ok: allPass, fingerprint, bars: results }, null, 2))
  process.exit(allPass ? 0 : 1)
}

const w = Math.max(4, ...results.map((r) => r.id.length))
console.log(`\n  ${spec.project ?? 'project'} — gate  (${fingerprint})\n`)
for (const r of results) {
  const mark = r.pass ? 'PASS' : 'FAIL'
  const actual = r.actual == null ? '—' : String(r.actual)
  console.log(`  ${mark}  ${r.id.padEnd(w)}  ${actual.padStart(8)}  ${r.compare} ${r.threshold}${r.note ? `   ${r.note}` : ''}`)
}
console.log(
  allPass
    ? `\n  ALL BARS PASS across ${spec.coverage?.members ?? '?'} ${spec.coverage?.axis ?? 'member'}(s). The loop may stop.\n`
    : `\n  ${results.filter((r) => !r.pass).length} of ${results.length} bars failing. Keep going.\n`
)
if (!only) console.log(`  Recorded. Run \`node tools/journal.mjs\` to fold this into PROGRESS.md.\n`)
process.exit(allPass ? 0 : 1)
